In [65]:
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv()

False

In [66]:
aseg = pd.read_csv("raw_data/aseg_volumes.txt", sep="\t", index_col=0)
demographics = pd.read_csv("raw_data/demographic_clean.txt", sep="\t", index_col=0)
lh_thickness = pd.read_csv("raw_data/lh_thickness.txt", sep="\t", index_col=0)
rh_thickness = pd.read_csv("raw_data/rh_thickness.txt", sep="\t", index_col=0)

aseg.index.name = "subject_id"
demographics.index.name = "subject_id"
lh_thickness.index.name = "subject_id"
rh_thickness.index.name = "subject_id"

In [67]:
aseg.head()

,Left-Lateral-Ventricle,Left-Inf-Lat-Vent,Left-Cerebellum-White-Matter,Left-Cerebellum-Cortex,Left-Thalamus,Left-Caudate,Left-Putamen,Left-Pallidum,3rd-Ventricle,4th-Ventricle,...,TotalGrayVol,SupraTentorialVol,SupraTentorialVolNotVent,MaskVol,BrainSegVol-to-eTIV,MaskVol-to-eTIV,lhSurfaceHoles,rhSurfaceHoles,SurfaceHoles,EstimatedTotalIntraCranialVol
subject_id,,,,,,,,,,,,,,,,,,,,,
sub-c100,14215.6,624.8,14358.2,60691.9,6620.6,3351.3,4842.5,2080.9,2075.3,1426.8,...,673666.776405,1055926.0,1017332.0,1713173.0,0.695198,0.986990,23.0,16.0,39.0,1.735755e+06
sub-c101,8966.3,311.8,17052.2,59275.5,7330.3,2713.5,4247.1,1908.3,811.2,1452.4,...,628339.741054,949768.0,929828.0,1565583.0,0.768107,1.091524,26.0,18.0,44.0,1.434309e+06
sub-c102,24019.1,992.9,13318.4,56942.6,8122.4,3764.5,4131.4,1944.0,1357.8,1606.5,...,648371.849842,1024981.0,970996.0,1732978.0,0.690476,1.026814,28.0,31.0,59.0,1.687724e+06
sub-c103,12844.8,368.1,14853.0,52052.4,8443.1,4177.4,5384.4,2267.8,1132.7,1951.7,...,698731.557592,1113090.0,1084337.0,1716927.0,0.744689,1.026397,38.0,57.0,95.0,1.672771e+06
sub-c104,11635.1,367.6,12874.0,53070.3,8730.9,3343.2,4048.1,1739.4,1123.8,1580.2,...,660457.163771,992450.0,967696.0,1703004.0,0.713292,1.079042,26.0,32.0,58.0,1.578255e+06

In [68]:
demographics.head()

            Code Group   Age Sex
subject_id
sub-c100    C100    HC  58.0   M
sub-c101    C101    HC  68.0   F
sub-c102    C102    HC  68.0   M
sub-c103    C103    HC  54.0   M
sub-c104    C104    HC  72.0   M

In [69]:
lh_thickness.head()

,lh_bankssts_thickness,lh_caudalanteriorcingulate_thickness,lh_caudalmiddlefrontal_thickness,lh_cuneus_thickness,lh_entorhinal_thickness,lh_fusiform_thickness,lh_inferiorparietal_thickness,lh_inferiortemporal_thickness,lh_isthmuscingulate_thickness,lh_lateraloccipital_thickness,...,lh_superiorparietal_thickness,lh_superiortemporal_thickness,lh_supramarginal_thickness,lh_frontalpole_thickness,lh_temporalpole_thickness,lh_transversetemporal_thickness,lh_insula_thickness,lh_MeanThickness_thickness,BrainSegVolNotVent,eTIV
subject_id,,,,,,,,,,,,,,,,,,,,,
sub-c100,2.450,2.479,2.511,1.944,3.209,2.644,2.490,2.764,2.015,2.185,...,2.164,2.764,2.449,2.611,3.528,2.435,2.949,2.45168,1168100.0,1.735755e+06
sub-c101,2.591,2.313,2.642,1.816,3.353,2.805,2.532,2.742,2.188,2.333,...,2.283,2.738,2.561,3.094,3.951,2.330,2.911,2.53737,1081763.0,1.434309e+06
sub-c102,2.450,2.457,2.541,1.853,3.306,2.663,2.430,2.763,2.369,2.177,...,2.337,2.703,2.662,2.932,3.389,2.523,2.868,2.47808,1111348.0,1.687724e+06
sub-c103,2.427,2.441,2.556,1.885,3.422,2.667,2.470,2.777,2.210,2.135,...,2.292,2.773,2.606,2.685,3.716,2.326,2.893,2.46320,1216941.0,1.672771e+06
sub-c104,2.558,2.429,2.694,1.936,3.169,2.697,2.351,2.742,2.137,1.996,...,2.247,2.637,2.550,2.784,3.785,2.565,2.943,2.47331,1101003.0,1.578255e+06

In [70]:
rh_thickness.head()

,rh_bankssts_thickness,rh_caudalanteriorcingulate_thickness,rh_caudalmiddlefrontal_thickness,rh_cuneus_thickness,rh_entorhinal_thickness,rh_fusiform_thickness,rh_inferiorparietal_thickness,rh_inferiortemporal_thickness,rh_isthmuscingulate_thickness,rh_lateraloccipital_thickness,...,rh_superiorparietal_thickness,rh_superiortemporal_thickness,rh_supramarginal_thickness,rh_frontalpole_thickness,rh_temporalpole_thickness,rh_transversetemporal_thickness,rh_insula_thickness,rh_MeanThickness_thickness,BrainSegVolNotVent,eTIV
subject_id,,,,,,,,,,,,,,,,,,,,,
sub-c100,2.398,2.267,2.592,1.984,3.309,2.741,2.473,2.907,2.063,2.329,...,2.119,2.899,2.537,2.743,4.049,2.667,2.836,2.49278,1168100.0,1.735755e+06
sub-c101,2.640,2.310,2.680,1.941,3.418,2.759,2.483,2.756,2.166,2.264,...,2.212,2.639,2.624,2.796,3.721,2.540,2.925,2.51928,1081763.0,1.434309e+06
sub-c102,2.477,2.259,2.655,1.852,3.282,2.775,2.425,2.723,2.561,2.092,...,2.066,2.618,2.678,2.713,2.919,2.157,2.816,2.42818,1111348.0,1.687724e+06
sub-c103,2.570,2.400,2.607,1.947,3.691,2.750,2.488,2.727,2.105,2.121,...,2.276,2.738,2.552,2.927,3.417,2.350,2.880,2.47422,1216941.0,1.672771e+06
sub-c104,2.417,2.293,2.549,1.969,3.279,2.566,2.416,2.831,2.176,2.187,...,2.150,2.791,2.465,2.818,3.401,2.221,3.055,2.48937,1101003.0,1.578255e+06

In [71]:
subject_ids = demographics.index.tolist()
print(f"Number of subjects: {len(subject_ids)}")

Number of subjects: 51

In [72]:
valid_subjects = []
invalid_subjects = []
for subject in subject_ids:
    if subject in aseg.index and subject in lh_thickness.index and subject in rh_thickness.index:
        valid_subjects.append(subject)
    else:
        invalid_subjects.append(subject)
print(f"Number of valid subjects: {len(valid_subjects)}")
print(f"Number of invalid subjects: {len(invalid_subjects)}")

Number of valid subjects: 51
Number of invalid subjects: 0

In [78]:
os.makedirs("processed_data", exist_ok=True)
patient_data = pd.merge(demographics, aseg, left_index=True, right_index=True)
patient_data = pd.merge(patient_data, lh_thickness, left_index=True, right_index=True)
patient_data = pd.merge(patient_data, rh_thickness, left_index=True, right_index=True)

patient_data.head()
print(patient_data.head())
print(f"Number of patients: {len(patient_data)}")
patient_data.to_csv("processed_data/patient_data.csv")

            Code Group   Age Sex  Left-Lateral-Ventricle  Left-Inf-Lat-Vent  \
subject_id
sub-c100    C100    HC  58.0   M                 14215.6              624.8
sub-c101    C101    HC  68.0   F                  8966.3              311.8
sub-c102    C102    HC  68.0   M                 24019.1              992.9
sub-c103    C103    HC  54.0   M                 12844.8              368.1
sub-c104    C104    HC  72.0   M                 11635.1              367.6

            Left-Cerebellum-White-Matter  Left-Cerebellum-Cortex  \
subject_id
sub-c100                         14358.2                 60691.9
sub-c101                         17052.2                 59275.5
sub-c102                         13318.4                 56942.6
sub-c103                         14853.0                 52052.4
sub-c104                         12874.0                 53070.3

            Left-Thalamus  Left-Caudate  ...  rh_superiorparietal_thickness  \
subject_id                               ...
sub-c100           6620.6        3351.3  ...                          2.119
sub-c101           7330.3        2713.5  ...                          2.212
sub-c102           8122.4        3764.5  ...                          2.066
sub-c103           8443.1        4177.4  ...                          2.276
sub-c104           8730.9        3343.2  ...                          2.150

            rh_superiortemporal_thickness  rh_supramarginal_thickness  \
subject_id
sub-c100                            2.899                       2.537
sub-c101                            2.639                       2.624
sub-c102                            2.618                       2.678
sub-c103                            2.738                       2.552
sub-c104                            2.791                       2.465

            rh_frontalpole_thickness  rh_temporalpole_thickness  \
subject_id
sub-c100                       2.743                      4.049
sub-c101                       2.796                      3.721
sub-c102                       2.713                      2.919
sub-c103                       2.927                      3.417
sub-c104                       2.818                      3.401

            rh_transversetemporal_thickness  rh_insula_thickness  \
subject_id
sub-c100                              2.667                2.836
sub-c101                              2.540                2.925
sub-c102                              2.157                2.816
sub-c103                              2.350                2.880
sub-c104                              2.221                3.055

            rh_MeanThickness_thickness  BrainSegVolNotVent        eTIV_y
subject_id
sub-c100                       2.49278           1168100.0  1.735755e+06
sub-c101                       2.51928           1081763.0  1.434309e+06
sub-c102                       2.42818           1111348.0  1.687724e+06
sub-c103                       2.47422           1216941.0  1.672771e+06
sub-c104                       2.48937           1101003.0  1.578255e+06

[5 rows x 142 columns]
Number of patients: 51

In [80]:
patient_data.columns.tolist()

['Code',
 'Group',
 'Age',
 'Sex',
 'Left-Lateral-Ventricle',
 'Left-Inf-Lat-Vent',
 'Left-Cerebellum-White-Matter',
 'Left-Cerebellum-Cortex',
 'Left-Thalamus',
 'Left-Caudate',
 'Left-Putamen',
 'Left-Pallidum',
 '3rd-Ventricle',
 '4th-Ventricle',
 'Brain-Stem',
 'Left-Hippocampus',
 'Left-Amygdala',
 'CSF',
 'Left-Accumbens-area',
 'Left-VentralDC',
 'Left-vessel',
 'Left-choroid-plexus',
 'Right-Lateral-Ventricle',
 'Right-Inf-Lat-Vent',
 'Right-Cerebellum-White-Matter',
 'Right-Cerebellum-Cortex',
 'Right-Thalamus',
 'Right-Caudate',
 'Right-Putamen',
 'Right-Pallidum',
 'Right-Hippocampus',
 'Right-Amygdala',
 'Right-Accumbens-area',
 'Right-VentralDC',
 'Right-vessel',
 'Right-choroid-plexus',
 '5th-Ventricle',
 'WM-hypointensities',
 'Left-WM-hypointensities',
 'Right-WM-hypointensities',
 'non-WM-hypointensities',
 'Left-non-WM-hypointensities',
 'Right-non-WM-hypointensities',
 'Optic-Chiasm',
 'CC_Posterior',
 'CC_Mid_Posterior',
 'CC_Central',
 'CC_Mid_Anterior',
 'CC_Anterior',
 'BrainSegVol',
 'BrainSegVolNotVent_x',
 'lhCortexVol',
 'rhCortexVol',
 'CortexVol',
 'lhCerebralWhiteMatterVol',
 'rhCerebralWhiteMatterVol',
 'CerebralWhiteMatterVol',
 'SubCortGrayVol',
 'TotalGrayVol',
 'SupraTentorialVol',
 'SupraTentorialVolNotVent',
 'MaskVol',
 'BrainSegVol-to-eTIV',
 'MaskVol-to-eTIV',
 'lhSurfaceHoles',
 'rhSurfaceHoles',
 'SurfaceHoles',
 'EstimatedTotalIntraCranialVol',
 'lh_bankssts_thickness',
 'lh_caudalanteriorcingulate_thickness',
 'lh_caudalmiddlefrontal_thickness',
 'lh_cuneus_thickness',
 'lh_entorhinal_thickness',
 'lh_fusiform_thickness',
 'lh_inferiorparietal_thickness',
 'lh_inferiortemporal_thickness',
 'lh_isthmuscingulate_thickness',
 'lh_lateraloccipital_thickness',
 'lh_lateralorbitofrontal_thickness',
 'lh_lingual_thickness',
 'lh_medialorbitofrontal_thickness',
 'lh_middletemporal_thickness',
 'lh_parahippocampal_thickness',
 'lh_paracentral_thickness',
 'lh_parsopercularis_thickness',
 'lh_parsorbitalis_thickness',
 'lh_parstriangularis_thickness',
 'lh_pericalcarine_thickness',
 'lh_postcentral_thickness',
 'lh_posteriorcingulate_thickness',
 'lh_precentral_thickness',
 'lh_precuneus_thickness',
 'lh_rostralanteriorcingulate_thickness',
 'lh_rostralmiddlefrontal_thickness',
 'lh_superiorfrontal_thickness',
 'lh_superiorparietal_thickness',
 'lh_superiortemporal_thickness',
 'lh_supramarginal_thickness',
 'lh_frontalpole_thickness',
 'lh_temporalpole_thickness',
 'lh_transversetemporal_thickness',
 'lh_insula_thickness',
 'lh_MeanThickness_thickness',
 'BrainSegVolNotVent_y',
 'eTIV_x',
 'rh_bankssts_thickness',
 'rh_caudalanteriorcingulate_thickness',
 'rh_caudalmiddlefrontal_thickness',
 'rh_cuneus_thickness',
 'rh_entorhinal_thickness',
 'rh_fusiform_thickness',
 'rh_inferiorparietal_thickness',
 'rh_inferiortemporal_thickness',
 'rh_isthmuscingulate_thickness',
 'rh_lateraloccipital_thickness',
 'rh_lateralorbitofrontal_thickness',
 'rh_lingual_thickness',
 'rh_medialorbitofrontal_thickness',
 'rh_middletemporal_thickness',
 'rh_parahippocampal_thickness',
 'rh_paracentral_thickness',
 'rh_parsopercularis_thickness',
 'rh_parsorbitalis_thickness',
 'rh_parstriangularis_thickness',
 'rh_pericalcarine_thickness',
 'rh_postcentral_thickness',
 'rh_posteriorcingulate_thickness',
 'rh_precentral_thickness',
 'rh_precuneus_thickness',
 'rh_rostralanteriorcingulate_thickness',
 'rh_rostralmiddlefrontal_thickness',
 'rh_superiorfrontal_thickness',
 'rh_superiorparietal_thickness',
 'rh_superiortemporal_thickness',
 'rh_supramarginal_thickness',
 'rh_frontalpole_thickness',
 'rh_temporalpole_thickness',
 'rh_transversetemporal_thickness',
 'rh_insula_thickness',
 'rh_MeanThickness_thickness',
 'BrainSegVolNotVent',
 'eTIV_y']